language Sentiment Analysis using different ML and DL algorithmns

1. importin dataset
2. Remove null data
3. Split target and feature columns
4. Lemmatization or Stemming , Stop words
5. OneHotEncoding
6. Embedding - Word2vec
7. LSTM - classifier deep learning algorithm
8. XGBOOST


https://colab.research.google.com/drive/1uQMCYJhgyHamrRSbv1f-h5Av85HTxzGp#scrollTo=R46pSZEjbVKJ

In [ ]:
import pandas as pd
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
## Connecting to drive
from google.colab import drive

drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


In [ ]:
# Reading dataset
df_train= pd.read_csv("/content/gdrive/MyDrive/Scaler Assignment/Kaggle_Competitions/Corona_Tweet_nlp_sentimentAnalysis/Corona_NLP_train.csv",encoding='latin-1')
df_test= pd.read_csv("/content/gdrive/MyDrive/Scaler Assignment/Kaggle_Competitions/Corona_Tweet_nlp_sentimentAnalysis/Corona_NLP_test.csv")

In [ ]:
df_train.head()

UserName  ScreenName   Location     TweetAt  \
0      3799       48751     London  16-03-2020   
1      3800       48752         UK  16-03-2020   
2      3801       48753  Vagabonds  16-03-2020   
3      3802       48754        NaN  16-03-2020   
4      3803       48755        NaN  16-03-2020   

                                       OriginalTweet           Sentiment  
0  @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...             Neutral  
1  advice Talk to your neighbours family to excha...            Positive  
2  Coronavirus Australia: Woolworths to give elde...            Positive  
3  My food stock is not the only one which is emp...            Positive  
4  Me, ready to go at supermarket during the #COV...  Extremely Negative

In [ ]:
df_train.head()

UserName  ScreenName   Location     TweetAt  \
0      3799       48751     London  16-03-2020   
1      3800       48752         UK  16-03-2020   
2      3801       48753  Vagabonds  16-03-2020   
3      3802       48754        NaN  16-03-2020   
4      3803       48755        NaN  16-03-2020   

                                       OriginalTweet           Sentiment  
0  @MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...             Neutral  
1  advice Talk to your neighbours family to excha...            Positive  
2  Coronavirus Australia: Woolworths to give elde...            Positive  
3  My food stock is not the only one which is emp...            Positive  
4  Me, ready to go at supermarket during the #COV...  Extremely Negative

In [ ]:
df_train.shape

(41157, 6)

In [ ]:
df_test.shape

(3798, 6)

In [ ]:
df_train.isnull().sum()

UserName            0
ScreenName          0
Location         8590
TweetAt             0
OriginalTweet       0
Sentiment           0
dtype: int64

In [ ]:
df_test.isnull().sum()

UserName           0
ScreenName         0
Location         834
TweetAt            0
OriginalTweet      0
Sentiment          0
dtype: int64

In [ ]:
## Get the Independent Features
tweet=df_train['OriginalTweet']

In [ ]:
# Target Feature
sentiment= df_train['Sentiment']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
LE = LabelEncoder()
sentiment = pd.Series(LE.fit_transform(sentiment))

In [ ]:
import tensorflow as tf


from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
# Data pre processing
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()
corpus=[]
for i in range(len(tweet)):

  review = re.sub('[^a-zA-Z]', ' ', tweet[i])

  # lowercase the tweets
  review= review.lower()

  # split the reviews
  review=review.split()

  # stemming and stopwords
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)


In [ ]:
## Single line with stemming snd stopwords done
corpus[1]

'advic talk neighbour famili exchang phone number creat contact list phone number neighbour school employ chemist gp set onlin shop account poss adequ suppli regular med order'

In [ ]:
vocabulary_size = 10000

#one hot encoding representation

onehot_repr=[one_hot(words,vocabulary_size)for words in corpus]

In [ ]:
# First tweet in dataset
corpus[50]

'everyth see current covid outbreak seen previou epidem pandem rise fear racism panic buy food medicin conspiraci theori prolifer quack cure http co pr npkx'

In [ ]:
# First onehot encoding for above tweet
onehot_repr[1]

[509,
 943,
 1185,
 2976,
 46,
 9462,
 1420,
 144,
 819,
 2392,
 9462,
 1420,
 1185,
 5513,
 8596,
 6387,
 8830,
 7394,
 1381,
 1760,
 5984,
 3465,
 8627,
 7682,
 8574,
 3536,
 2496]

### Embedding Representation

In [ ]:
# Sentence length - consider by checking number of avg words in each tweets
sent_length=25
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[9458 8382 9726 ...    0    0    0]
 [1185 2976   46 ... 8574 3536 2496]
 [9512 5093 6115 ...    0    0    0]
 ...
 [4423  416 2374 ...    0    0    0]
 [6568  275 4777 ...    0    0    0]
 [5708 9987 7277 ... 7008 4888 8319]]


In [ ]:
embedded_docs[0]

array([9458, 8382, 9726,  781, 4386, 7979, 5553, 7290, 3956, 4386, 7979,
       3932, 7265, 4386, 7979, 1872,    0,    0,    0,    0,    0,    0,
          0,    0,    0], dtype=int32)

## Creating Model- LSTM

In [ ]:
## Creating model
from tensorflow.keras.layers import Bidirectional
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(vocabulary_size,embedding_vector_features,input_length=sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(64, activation='relu'))
model.add(Dense(1,activation='softmax'))

# Compile the model with softmax and categorical cross-entropy
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 25, 40)            400000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              112800    
 l)                                                              
                                                                 
 dense (Dense)               (None, 64)                12864     
                                                                 
 dense_1 (Dense)             (None, 1)                 65        
                                                                 
Total params: 525,729
Trainable params: 525,729
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedded_docs),sentiment.shape

(41157, (41157,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(sentiment)

In [ ]:
X_final.shape,y_final.shape

((41157, 25), (41157,))

In [ ]:
## train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

## Training Model

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=128)

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/dispatch.py:1176: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(None, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return dispatch_target(*args, **kwargs)


216/216 [==============================] - 22s 87ms/step - loss: 0.0000e+00 - accuracy: 0.1608 - val_loss: 0.0000e+00 - val_accuracy: 0.1612
Epoch 2/10
216/216 [==============================] - 18s 83ms/step - loss: 0.0000e+00 - accuracy: 0.1608 - val_loss: 0.0000e+00 - val_accuracy: 0.1612
Epoch 3/10
216/216 [==============================] - 17s 81ms/step - loss: 0.0000e+00 - accuracy: 0.1608 - val_loss: 0.0000e+00 - val_accuracy: 0.1612
Epoch 4/10
216/216 [==============================] - 19s 87ms/step - loss: 0.0000e+00 - accuracy: 0.1608 - val_loss: 0.0000e+00 - val_accuracy: 0.1612
Epoch 5/10
216/216 [==============================] - 18s 81ms/step - loss: 0.0000e+00 - accuracy: 0.1608 - val_loss: 0.0000e+00 - val_accuracy: 0.1612
Epoch 6/10
216/216 [==============================] - 18s 82ms/step - loss: 0.0000e+00 - accuracy: 0.1608 - val_loss: 0.0000e+00 - val_accuracy: 0.1612
Epoch 7/10
216/216 [==============================] - 19s 88ms/step - loss: 0.0000e+00 - accuracy: 

## Trying with XGBoost Classifier

In [ ]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier


xg_tuned_parameters = [{'gamma': [15,20],
                        'learning_rate':[0.6,0.8]}]
xg_mod_tunned = XGBClassifier()
xg_grid = GridSearchCV(estimator=xg_mod_tunned,param_grid=xg_tuned_parameters,cv=2)
xg_grid_model = xg_grid.fit(X_train,y_train)
print('Best Parameters:- ',xg_grid_model.best_params_)

# Evaluate the model with the best hyperparameters
best_xb = XGBClassifier(**xg_grid_model.best_params_)
best_xb.fit(X_train, y_train)
accuracy = best_xb.score(X_test, y_test)
accuracy

Best Parameters:-  {'gamma': 20, 'learning_rate': 0.6}


0.30054483875717863

In [ ]:
'''from tensorflow import keras
from keras.utils import np_utils

model = keras.models.Sequential(
     model.add(Embedding(vocabulary_size,embedding_vector_features,input_length=sent_length))
    keras.layers.Embedding(len(word_index)+1,
                           200,
                           input_length=max_len,
                           weights=[embedding_matrix],
                           trainable=False),
    keras.layers.SpatialDropout1D(.5),
    keras.layers.Bidirectional(keras.layers.LSTM(100, recurrent_dropout=.3)),
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(.6),
    keras.layers.Dense(1024, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(.6),

    keras.layers.Dense(5, activation='softmax')
])

model.compile(optimizer=keras.optimizers.Adam(learning_rate=.01),
              loss='categorical_crossentropy',
              metrics='accuracy')

model.summary()
'''

"from tensorflow import keras\nfrom keras.utils import np_utils\n\nmodel = keras.models.Sequential(\n     model.add(Embedding(vocabulary_size,embedding_vector_features,input_length=sent_length))\n    keras.layers.Embedding(len(word_index)+1,\n                           200,\n                           input_length=max_len,\n                           weights=[embedding_matrix],\n                           trainable=False),\n    keras.layers.SpatialDropout1D(.5),\n    keras.layers.Bidirectional(keras.layers.LSTM(100, recurrent_dropout=.3)),\n    keras.layers.BatchNormalization(),\n    keras.layers.Dropout(.6),\n    keras.layers.Dense(1024, activation='relu'),\n    keras.layers.BatchNormalization(),\n    keras.layers.Dropout(.6),\n    \n    keras.layers.Dense(5, activation='softmax')\n])\n\nmodel.compile(optimizer=keras.optimizers.Adam(learning_rate=.01),\n              loss='categorical_crossentropy',\n              metrics='accuracy')\n\nmodel.summary()\n"

## Adding drop out

In [ ]:
from tensorflow.keras.layers import Dropout,Bidirectional, SpatialDropout1D,BatchNormalization
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(vocabulary_size,embedding_vector_features,input_length=sent_length))
model.add(SpatialDropout1D(.5))
model.add(Dropout(0.2))
model.add(Bidirectional(LSTM(100,recurrent_dropout=.3)))
model.add(BatchNormalization())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1,activation='softmax'))

# Compile the model with softmax and categorical cross-entropy
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics='accuracy')

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/dispatch.py:1176: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(None, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return dispatch_target(*args, **kwargs)


431/431 [==============================] - 41s 87ms/step - loss: 0.0000e+00 - accuracy: 0.1608 - val_loss: 0.0000e+00 - val_accuracy: 0.1612
Epoch 2/10
431/431 [==============================] - 43s 101ms/step - loss: 0.0000e+00 - accuracy: 0.1608 - val_loss: 0.0000e+00 - val_accuracy: 0.1612
Epoch 3/10
431/431 [==============================] - 37s 86ms/step - loss: 0.0000e+00 - accuracy: 0.1608 - val_loss: 0.0000e+00 - val_accuracy: 0.1612
Epoch 4/10
431/431 [==============================] - 37s 85ms/step - loss: 0.0000e+00 - accuracy: 0.1608 - val_loss: 0.0000e+00 - val_accuracy: 0.1612
Epoch 5/10
431/431 [==============================] - 37s 87ms/step - loss: 0.0000e+00 - accuracy: 0.1608 - val_loss: 0.0000e+00 - val_accuracy: 0.1612
Epoch 6/10
431/431 [==============================] - 37s 86ms/step - loss: 0.0000e+00 - accuracy: 0.1608 - val_loss: 0.0000e+00 - val_accuracy: 0.1612
Epoch 7/10
431/431 [==============================] - 37s 85ms/step - loss: 0.0000e+00 - accuracy:

## Performance and Accuracy

In [ ]:
y_pred=model.predict(X_test)

425/425 [==============================] - 4s 9ms/step


In [ ]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred)

array([[   0, 1753,    0,    0,    0],
       [   0, 2190,    0,    0,    0],
       [   0, 3300,    0,    0,    0],
       [   0, 2518,    0,    0,    0],
       [   0, 3821,    0,    0,    0]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.16124282138123988

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1753
           1       0.16      1.00      0.28      2190
           2       0.00      0.00      0.00      3300
           3       0.00      0.00      0.00      2518
           4       0.00      0.00      0.00      3821

    accuracy                           0.16     13582
   macro avg       0.03      0.20      0.06     13582
weighted avg       0.03      0.16      0.04     13582



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Trying with AvgWord2Vec and lemmatization

In [ ]:
!pip install gensim

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [ ]:
'''import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king = wv['king']'''

"import gensim.downloader as api\n\nwv = api.load('word2vec-google-news-300')\n\nvec_king = wv['king']"

In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer=WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
corpus = []
for i in range(0, len(tweet)):
    review = re.sub('[^a-zA-Z]', ' ', tweet[i])
    review = review.lower()
    review = review.split()

    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [ ]:
## Lets train Word2vec from scratch
model=gensim.models.Word2Vec(words)

In [ ]:
## To Get All the Vocabulary
# model.wv.index_to_key

In [ ]:
model.corpus_count

41157

In [ ]:
model.epochs

5

In [ ]:
words[0]

['menyrbie',
 'phil',
 'gahan',
 'chrisitv',
 'http',
 'co',
 'ifz',
 'fan',
 'pa',
 'and',
 'http',
 'co',
 'xx',
 'ghgfzcc',
 'and',
 'http',
 'co',
 'nlzdxno']

In [ ]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)

    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [ ]:
!pip install tqdm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#tqdm is a Python library that provides a fast, extensible progress bar for loops and iterable objects
from tqdm import tqdm

In [ ]:
#apply for the entire sentences
import numpy as np
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

 86%|████████▌ | 35441/41157 [00:40<00:04, 1255.08it/s]/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 41157/41157 [00:44<00:00, 918.82it/s] 


In [ ]:
##independent Features
X_new=np.array(X)

<ipython-input-121-c24378517c84>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_new=np.array(X)


In [ ]:
X_new.shape

(41157,)

In [ ]:
X_new[0].shape

(100,)

In [ ]:
y

Extremely Negative  Extremely Positive  Negative  Neutral  Positive
0                       0                   0         0        1         0
1                       0                   0         0        0         1
2                       0                   0         0        0         1
3                       0                   0         0        0         1
4                       1                   0         0        0         0
...                   ...                 ...       ...      ...       ...
41152                   0                   0         0        1         0
41153                   1                   0         0        0         0
41154                   0                   0         0        0         1
41155                   0                   0         0        1         0
41156                   0                   0         1        0         0

[41157 rows x 5 columns]

In [ ]:
## Dependent Features
## Output Features
y = df_train[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.get_dummies(y['Sentiment'])
y=y.drop(3556)
y=y.iloc[:,0].values

In [ ]:
X[0].reshape(1,-1).shape

(1, 100)

In [ ]:
dff.shape

(41157, 100)

In [ ]:
## this is the final independent features
dff=pd.DataFrame()
for i in tqdm(range(0,len(X))):
    dff=dff.append(pd.DataFrame(X[i].reshape(1,-1)),ignore_index=True)


  0%|          | 0/41157 [00:00<?, ?it/s]<ipython-input-123-615ec39b3907>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dff=dff.append(pd.DataFrame(X[i].reshape(1,-1)),ignore_index=True)
100%|██████████| 41157/41157 [00:36<00:00, 1135.64it/s]


In [ ]:
dff.shape

(41157, 100)

In [ ]:
dff.head()

0         1         2         3         4         5         6   \
0 -0.088735  0.681209 -0.421966  0.095742  0.510445 -0.614078  0.138579   
1 -0.142215  0.242666  0.012235 -0.566202 -0.106632 -0.442899 -0.474804   
2 -0.078233  0.040508 -0.090023 -0.240008  0.188042 -0.638945  0.138407   
3 -0.116518 -0.059052 -0.089955 -0.440923 -0.331429 -0.163654 -0.665887   
4 -0.096773  0.019585  0.088728 -0.393668 -0.358834 -0.700447 -0.378295   

         7         8         9   ...        90        91        92        93  \
0  0.698621 -1.365274 -0.543150  ...  0.204912 -0.007470  0.313374 -0.659928   
1  0.075512  0.207749 -0.261367  ... -0.036284 -0.116901 -0.489550  0.521102   
2  0.652051 -0.728114 -0.348359  ...  0.484039 -0.177292 -0.275914 -0.038371   
3  0.304848 -0.469007 -1.029923  ... -0.255022  0.003948 -0.543556  0.175896   
4  0.196079 -0.438456 -1.051616  ... -0.115988 -0.077116 -0.418969  0.407812   

         94        95        96        97        98        99  
0  0.800893  0.827747 -0.128340 -0.062563  0.176434 -1.111752  
1  0.136668 -0.066931 -0.173476 -0.166862 -0.541419  0.242648  
2  0.141057  0.381715 -0.197512  0.071532 -0.183906 -0.332749  
3  0.054357  0.110225 -0.075110 -0.173247 -0.190668  0.233456  
4  0.039320  0.425451 -0.134457 -0.216405 -0.019132  0.240257  

[5 rows x 100 columns]

In [ ]:
dff.shape

(41157, 100)

In [ ]:
null_mask = dff.isnull()
null_row_mask = null_mask.any(axis=1)
null_row_indices = null_row_mask[null_row_mask].index
null_row_indices

Int64Index([35565], dtype='int64')

In [ ]:
dff=dff.drop(35565)


In [ ]:
## Independent Feature
X=dff

In [ ]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [ ]:
X_train.head()

0         1         2         3         4         5         6   \
26793 -0.414113  0.097749  0.192717 -0.452347 -0.576288 -0.715180  0.459532   
6592  -0.012985 -0.033088  0.122997 -0.303690 -0.262549 -0.362952 -0.219830   
29427 -0.234532  0.306273  0.015366 -0.685565 -0.431703 -0.705268  0.403395   
37613  0.025446  0.177579  0.239660  0.104333 -0.192385 -0.834000 -0.178276   
20084 -0.253775  0.219871  0.261515 -0.304862 -0.892193 -0.595882  0.553128   

             7         8         9   ...        90        91        92  \
26793 -0.001316 -0.315036  0.068361  ...  0.468357 -0.128354 -0.360095   
6592   0.480420  0.089716 -0.371162  ...  0.303006 -0.153666 -0.251792   
29427  0.096910 -0.642943 -0.225533  ...  1.027119 -0.034627  0.377019   
37613  0.065179 -0.480818 -0.595574  ... -0.169561 -0.035339  0.362376   
20084  0.056757 -0.205481 -0.121721  ...  0.461290  0.034070 -0.137220   

             93        94        95        96        97        98        99  
26793 -0.023733  0.569564  0.332235 -0.421204 -0.262662  0.003614  0.149561  
6592   0.451440  0.167437 -0.289790  0.119144 -0.253867 -0.410849  0.542802  
29427 -0.256028  0.669823  0.222155 -0.291170  0.232076 -0.016287 -0.651864  
37613  0.770941 -0.146985  0.522778  0.457772  0.564172 -0.063423 -0.430065  
20084 -0.022284  0.424957  0.073564 -0.310328 -0.549941 -0.066364 -0.090583  

[5 rows x 100 columns]

In [ ]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [ ]:
# Random forestClassifier
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()


classifier.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred=classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.8609086491739553


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      1.00      0.93      7088
           1       0.44      0.00      0.01      1144

    accuracy                           0.86      8232
   macro avg       0.65      0.50      0.47      8232
weighted avg       0.80      0.86      0.80      8232



## XGBoost Classifier with Avg-word2vec

In [ ]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier


# Evaluate the model with the best hyperparameters
best_xb = XGBClassifier(gamma=20, learning_rate=0.6)
best_xb.fit(X_train, y_train)
accuracy = best_xb.score(X_test, y_test)
accuracy

0.8606656948493683

## We are able to get 86 % accuracy